"""establish relationship between users and posts

Revision ID: 3c40f20d9970
Revises: 000ac2aaea38
Create Date: 2026-05-01 08:49:30.290115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c40f20d9970'
down_revision: Union[str, Sequence[str], None] = '000ac2aaea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('posts',schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_posts_users_id','users',['user_id'],['id'],ondelete = 'CASCADE')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
